import type {
  Usuario,
  Movil,
  Traslado,
  EventoTimeline,
} from "./types"

// ── Usuarios de prueba ──
export const MOCK_USUARIOS: Usuario[] = [
  {
    id: "u1",
    nombre: "Carlos",
    apellido: "Ramirez",
    rol: "central",
    turno: "diurno",
    email: "carlos.ramirez@hospital.co",
  },
  {
    id: "u2",
    nombre: "Maria",
    apellido: "Lopez",
    rol: "enfermera",
    servicio: "UCI Adultos",
    turno: "diurno",
    email: "maria.lopez@hospital.co",
  },
  {
    id: "u3",
    nombre: "Andres",
    apellido: "Garcia",
    rol: "conductor",
    turno: "diurno",
    email: "andres.garcia@hospital.co",
  },
  {
    id: "u4",
    nombre: "Laura",
    apellido: "Martinez",
    rol: "enfermera",
    servicio: "Urgencias",
    turno: "nocturno",
    email: "laura.martinez@hospital.co",
  },
  {
    id: "u5",
    nombre: "Jorge",
    apellido: "Hernandez",
    rol: "medico",
    servicio: "UCI Adultos",
    turno: "diurno",
    email: "jorge.hernandez@hospital.co",
  },
  {
    id: "u6",
    nombre: "Sandra",
    apellido: "Restrepo",
    rol: "enfermera",
    servicio: "Hospitalizacion",
    turno: "diurno",
    email: "sandra.restrepo@hospital.co",
  },
]

// ── Moviles / Ambulancias ──
export const MOCK_MOVILES: Movil[] = [
  {
    id: "m1",
    numero: "M-01",
    placa: "TXR-456",
    tipo: "medicalizada",
    estado: "disponible",
    tripulacion: [
      { id: "t1", nombre: "Pedro Duarte", rol: "conductor" },
      { id: "t2", nombre: "Ana Mejia", rol: "medico" },
      { id: "t3", nombre: "Luis Rios", rol: "enfermero" },
    ],
  },
  {
    id: "m2",
    numero: "M-02",
    placa: "TXR-789",
    tipo: "basica",
    estado: "en_servicio",
    trasladoActual: "tr3",
    ubicacion: "En camino a Clinica Los Rosales",
    tripulacion: [
      { id: "t4", nombre: "Andres Garcia", rol: "conductor" },
      { id: "t5", nombre: "Diana Castro", rol: "auxiliar" },
    ],
  },
  {
    id: "m3",
    numero: "M-03",
    placa: "TXR-012",
    tipo: "medicalizada",
    estado: "disponible",
    tripulacion: [
      { id: "t6", nombre: "Felipe Ortiz", rol: "conductor" },
      { id: "t7", nombre: "Carmen Vega", rol: "medico" },
      { id: "t8", nombre: "Rosa Pinto", rol: "enfermero" },
    ],
  },
  {
    id: "m4",
    numero: "M-04",
    placa: "TXR-345",
    tipo: "basica",
    estado: "retornando",
    ubicacion: "Av. 30 de Agosto con Cll 17",
    tripulacion: [
      { id: "t9", nombre: "Marco Salazar", rol: "conductor" },
      { id: "t10", nombre: "Jenny Torres", rol: "auxiliar" },
    ],
  },
  {
    id: "m5",
    numero: "M-05",
    placa: "TXR-678",
    tipo: "TAM",
    estado: "mantenimiento",
    tripulacion: [],
  },
  {
    id: "m6",
    numero: "M-06",
    placa: "TXR-901",
    tipo: "basica",
    estado: "en_servicio",
    trasladoActual: "tr5",
    ubicacion: "Hospital San Pedro y San Pablo",
    tripulacion: [
      { id: "t11", nombre: "Esteban Mora", rol: "conductor" },
      { id: "t12", nombre: "Paola Ruiz", rol: "auxiliar" },
    ],
  },
  {
    id: "m7",
    numero: "M-07",
    placa: "TXR-234",
    tipo: "medicalizada",
    estado: "disponible",
    tripulacion: [
      { id: "t13", nombre: "Ivan Cortes", rol: "conductor" },
      { id: "t14", nombre: "Natalia Diaz", rol: "medico" },
      { id: "t15", nombre: "Oscar Pena", rol: "enfermero" },
    ],
  },
  {
    id: "m8",
    numero: "M-08",
    placa: "TXR-567",
    tipo: "basica",
    estado: "fuera_servicio",
    tripulacion: [],
  },
]

// ── Traslados ──
export const MOCK_TRASLADOS: Traslado[] = [
  {
    id: "tr1",
    tipo: "secundario",
    prioridad: "urgente",
    estado: "pendiente",
    paciente: {
      nombreCompleto: "Juan David Perez Gomez",
      documento: "1088345678",
      tipoDocumento: "CC",
      edad: 45,
      sexo: "M",
      eps: "Nueva EPS",
      tipoAfiliacion: "contributivo",
      diagnostico: "IAM con elevacion ST - Requiere cateterismo cardiaco",
      cama: "UCI-A12",
    },
    signosVitales: {
      tensionSistolica: 90,
      tensionDiastolica: 60,
      frecuenciaCardiaca: 110,
      frecuenciaRespiratoria: 24,
      spo2: 92,
      temperatura: 36.8,
      glasgow: 15,
    },
    servicioOrigen: "UCI Adultos",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "Hemodinamia",
    institucionDestino: "Clinica Los Rosales",
    motivoTraslado: "Cateterismo cardiaco urgente - No disponible en la institucion",
    requiereMedico: true,
    notaEnfermeria: "Paciente con dolor toracico persistente, infusion de heparina en curso. Acceso venoso central subclavio derecho. Requiere monitoreo continuo durante traslado.",
    observaciones: "Llevar bomba de infusion y monitor cardiaco",
    fechaSolicitud: "2026-03-04T06:30:00",
    enfermeroSolicitante: "Maria Lopez",
    enfermeroSolicitanteId: "u2",
    equipoRequerido: ["Monitor cardiaco", "Bomba de infusion", "Oxigeno"],
  },
  {
    id: "tr2",
    tipo: "primario",
    prioridad: "programado",
    estado: "pendiente",
    paciente: {
      nombreCompleto: "Ana Sofia Rodriguez Cardona",
      documento: "42156789",
      tipoDocumento: "CC",
      edad: 67,
      sexo: "F",
      eps: "Sura EPS",
      tipoAfiliacion: "contributivo",
      diagnostico: "Fractura de cadera derecha - Programada para cirugia",
      cama: "HOSP-305",
    },
    signosVitales: {
      tensionSistolica: 130,
      tensionDiastolica: 85,
      frecuenciaCardiaca: 78,
      frecuenciaRespiratoria: 18,
      spo2: 97,
      temperatura: 36.5,
      glasgow: 15,
    },
    servicioOrigen: "Hospitalizacion",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "Imagenologia",
    institucionDestino: "Clinica Comfamiliar",
    motivoTraslado: "TAC preoperatorio - Equipo en mantenimiento",
    requiereMedico: false,
    notaEnfermeria: "Paciente orientada, colaboradora. Inmovilizacion con ferula en MID. Dolor controlado con analgesia oral. Alergia a la Dipirona.",
    observaciones: "Paciente con dificultad para la movilizacion, requiere camilla",
    fechaSolicitud: "2026-03-04T07:15:00",
    enfermeroSolicitante: "Sandra Restrepo",
    enfermeroSolicitanteId: "u6",
    equipoRequerido: ["Tabla espinal"],
  },
  {
    id: "tr3",
    tipo: "secundario",
    prioridad: "urgente",
    estado: "en_traslado",
    paciente: {
      nombreCompleto: "Carlos Alberto Mesa Rios",
      documento: "10234567",
      tipoDocumento: "CC",
      edad: 55,
      sexo: "M",
      eps: "Salud Total",
      tipoAfiliacion: "contributivo",
      diagnostico: "ACV isquemico agudo - Ventana trombolisis",
      cama: "URG-07",
    },
    signosVitales: {
      tensionSistolica: 180,
      tensionDiastolica: 100,
      frecuenciaCardiaca: 95,
      frecuenciaRespiratoria: 22,
      spo2: 94,
      temperatura: 37.2,
      glasgow: 12,
    },
    servicioOrigen: "Urgencias",
    institucionOrigen: "ESE Salud Pereira",
    servicioDestino: "UCI Adultos",
    institucionDestino: "Hospital Universitario San Jorge",
    motivoTraslado: "Requiere trombolisis - UCI disponible en destino",
    requiereMedico: true,
    notaEnfermeria: "Paciente somnoliento, hemiparesia izquierda. Glasgow 12 (O4-V3-M5). Con oxigeno por canula nasal a 3L. Infusion SSN 0.9%.",
    observaciones: "Urgente, ventana terapeutica limitada",
    fechaSolicitud: "2026-03-04T05:45:00",
    fechaAsignacion: "2026-03-04T05:52:00",
    fechaInicio: "2026-03-04T06:10:00",
    enfermeroSolicitante: "Laura Martinez",
    enfermeroSolicitanteId: "u4",
    movilAsignada: "m2",
    operadorCentral: "Carlos Ramirez",
    conductorAsignado: "Andres Garcia",
    equipoRequerido: ["Monitor cardiaco", "Oxigeno", "Aspirador de secreciones"],
  },
  {
    id: "tr4",
    tipo: "primario",
    prioridad: "programado",
    estado: "completado",
    paciente: {
      nombreCompleto: "Lucia Fernanda Gomez Parra",
      documento: "25890123",
      tipoDocumento: "CC",
      edad: 32,
      sexo: "F",
      eps: "Coomeva EPS",
      tipoAfiliacion: "contributivo",
      diagnostico: "Embarazo de 38 semanas - Control fetal",
      cama: "GIN-202",
    },
    signosVitales: {
      tensionSistolica: 120,
      tensionDiastolica: 75,
      frecuenciaCardiaca: 82,
      frecuenciaRespiratoria: 17,
      spo2: 98,
      temperatura: 36.6,
      glasgow: 15,
    },
    servicioOrigen: "Ginecologia",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "Ecografia",
    institucionDestino: "Clinica San Rafael",
    motivoTraslado: "Ecografia doppler fetal de control",
    requiereMedico: false,
    notaEnfermeria: "Paciente estable, con movimientos fetales positivos. Sin contracciones. Via oral tolerada.",
    observaciones: "",
    fechaSolicitud: "2026-03-04T04:00:00",
    fechaAsignacion: "2026-03-04T04:10:00",
    fechaInicio: "2026-03-04T04:30:00",
    fechaFinalizacion: "2026-03-04T05:45:00",
    enfermeroSolicitante: "Maria Lopez",
    enfermeroSolicitanteId: "u2",
    movilAsignada: "m4",
    operadorCentral: "Carlos Ramirez",
    conductorAsignado: "Marco Salazar",
    equipoRequerido: [],
  },
  {
    id: "tr5",
    tipo: "secundario",
    prioridad: "urgente",
    estado: "en_origen",
    paciente: {
      nombreCompleto: "Miguel Angel Torres Velez",
      documento: "1088901234",
      tipoDocumento: "CC",
      edad: 8,
      sexo: "M",
      eps: "Medimas",
      tipoAfiliacion: "subsidiado",
      diagnostico: "Politraumatismo por accidente de transito",
      cama: "PED-105",
    },
    signosVitales: {
      tensionSistolica: 95,
      tensionDiastolica: 55,
      frecuenciaCardiaca: 130,
      frecuenciaRespiratoria: 28,
      spo2: 93,
      temperatura: 37.5,
      glasgow: 13,
    },
    servicioOrigen: "Pediatria",
    institucionOrigen: "Hospital Infantil",
    servicioDestino: "UCI Pediatrica",
    institucionDestino: "Hospital Universitario San Jorge",
    motivoTraslado: "Requiere UCI Pediatrica - No disponible en la institucion",
    requiereMedico: true,
    notaEnfermeria: "Nino con trauma craneoencefalico moderado y fractura de femur izquierdo. Collar cervical insitu. Infusion de cristaloides en curso.",
    observaciones: "Pediatrico, manejar con precaucion. Madre acompanante autorizada.",
    fechaSolicitud: "2026-03-04T06:00:00",
    fechaAsignacion: "2026-03-04T06:08:00",
    fechaInicio: "2026-03-04T06:25:00",
    enfermeroSolicitante: "Laura Martinez",
    enfermeroSolicitanteId: "u4",
    movilAsignada: "m6",
    operadorCentral: "Carlos Ramirez",
    conductorAsignado: "Esteban Mora",
    equipoRequerido: ["Monitor cardiaco", "Oxigeno", "Collar cervical", "Tabla espinal"],
  },
  {
    id: "tr6",
    tipo: "primario",
    prioridad: "programado",
    estado: "asignado",
    paciente: {
      nombreCompleto: "Rosa Elena Cardenas Zapata",
      documento: "24567890",
      tipoDocumento: "CC",
      edad: 72,
      sexo: "F",
      eps: "Mutual SER",
      tipoAfiliacion: "subsidiado",
      diagnostico: "ERC estadio IV - Control nefrologico",
      cama: "MED-408",
    },
    signosVitales: {
      tensionSistolica: 150,
      tensionDiastolica: 90,
      frecuenciaCardiaca: 70,
      frecuenciaRespiratoria: 19,
      spo2: 96,
      temperatura: 36.4,
      glasgow: 15,
    },
    servicioOrigen: "Medicina Interna",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "Nefrologia",
    institucionDestino: "Clinica Comfamiliar",
    motivoTraslado: "Valoracion por Nefrologia para inicio de dialisis",
    requiereMedico: false,
    notaEnfermeria: "Paciente orientada, con edema de miembros inferiores. Dieta hiposodica. Medicamentos: Losartan, Furosemida, Eritropoyetina.",
    observaciones: "Paciente con movilidad reducida",
    fechaSolicitud: "2026-03-04T07:00:00",
    fechaAsignacion: "2026-03-04T07:20:00",
    enfermeroSolicitante: "Sandra Restrepo",
    enfermeroSolicitanteId: "u6",
    movilAsignada: "m1",
    operadorCentral: "Carlos Ramirez",
    equipoRequerido: [],
  },
  {
    id: "tr7",
    tipo: "secundario",
    prioridad: "urgente",
    estado: "pendiente",
    paciente: {
      nombreCompleto: "Fernando Jose Arias Cano",
      documento: "10789012",
      tipoDocumento: "CC",
      edad: 60,
      sexo: "M",
      eps: "Sanitas",
      tipoAfiliacion: "contributivo",
      diagnostico: "Sepsis de origen pulmonar - Requiere UCI",
      cama: "URG-15",
    },
    signosVitales: {
      tensionSistolica: 80,
      tensionDiastolica: 50,
      frecuenciaCardiaca: 120,
      frecuenciaRespiratoria: 30,
      spo2: 88,
      temperatura: 39.2,
      glasgow: 14,
    },
    servicioOrigen: "Urgencias",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "UCI Adultos",
    institucionDestino: "Clinica Los Rosales",
    motivoTraslado: "UCI llena en nuestra institucion - Requiere ventilacion mecanica",
    requiereMedico: true,
    notaEnfermeria: "Paciente febril, taquicardico, con signos de dificultad respiratoria. Antibioticos IV en curso (Piperacilina/Tazobactam). Acceso venoso periferico bilateral.",
    observaciones: "Prioridad alta, posible necesidad de intubacion en traslado",
    fechaSolicitud: "2026-03-04T07:45:00",
    enfermeroSolicitante: "Maria Lopez",
    enfermeroSolicitanteId: "u2",
    equipoRequerido: ["Monitor cardiaco", "Oxigeno", "Ventilador mecanico", "Bomba de infusion", "Aspirador de secreciones"],
  },
  {
    id: "tr8",
    tipo: "primario",
    prioridad: "programado",
    estado: "pendiente",
    paciente: {
      nombreCompleto: "Patricia Morales de Gutierrez",
      documento: "25123456",
      tipoDocumento: "CC",
      edad: 50,
      sexo: "F",
      eps: "Compensar",
      tipoAfiliacion: "contributivo",
      diagnostico: "Ca de mama - Control oncologico",
      cama: "HOSP-210",
    },
    signosVitales: {
      tensionSistolica: 125,
      tensionDiastolica: 80,
      frecuenciaCardiaca: 75,
      frecuenciaRespiratoria: 16,
      spo2: 99,
      temperatura: 36.5,
      glasgow: 15,
    },
    servicioOrigen: "Hospitalizacion",
    institucionOrigen: "Hospital Universitario San Jorge",
    servicioDestino: "Oncologia",
    institucionDestino: "Centro Medico Especializado",
    motivoTraslado: "Sesion de quimioterapia programada",
    requiereMedico: false,
    notaEnfermeria: "Paciente estable, orientada. Port-a-cath funcional. Sin nauseas actualmente. Hb 10.2.",
    observaciones: "",
    fechaSolicitud: "2026-03-04T08:00:00",
    enfermeroSolicitante: "Sandra Restrepo",
    enfermeroSolicitanteId: "u6",
    equipoRequerido: [],
  },
]

// ── Eventos Timeline ──
export const MOCK_EVENTOS: EventoTimeline[] = [
  { id: "e1", trasladoId: "tr3", tipo: "pendiente", descripcion: "Solicitud de traslado creada", fecha: "2026-03-04T05:45:00", usuario: "Laura Martinez" },
  { id: "e2", trasladoId: "tr3", tipo: "asignado", descripcion: "Movil M-02 asignada por Central", fecha: "2026-03-04T05:52:00", usuario: "Carlos Ramirez" },
  { id: "e3", trasladoId: "tr3", tipo: "en_camino", descripcion: "Movil en camino al origen", fecha: "2026-03-04T06:00:00", usuario: "Andres Garcia" },
  { id: "e4", trasladoId: "tr3", tipo: "en_origen", descripcion: "Movil llego al origen - Recogiendo paciente", fecha: "2026-03-04T06:10:00", usuario: "Andres Garcia" },
  { id: "e5", trasladoId: "tr3", tipo: "en_traslado", descripcion: "Paciente a bordo, en traslado al destino", fecha: "2026-03-04T06:20:00", usuario: "Andres Garcia" },
  { id: "e6", trasladoId: "tr5", tipo: "pendiente", descripcion: "Solicitud de traslado creada", fecha: "2026-03-04T06:00:00", usuario: "Laura Martinez" },
  { id: "e7", trasladoId: "tr5", tipo: "asignado", descripcion: "Movil M-06 asignada por Central", fecha: "2026-03-04T06:08:00", usuario: "Carlos Ramirez" },
  { id: "e8", trasladoId: "tr5", tipo: "en_camino", descripcion: "Movil en camino al origen", fecha: "2026-03-04T06:15:00", usuario: "Esteban Mora" },
  { id: "e9", trasladoId: "tr5", tipo: "en_origen", descripcion: "Movil en origen - Recibiendo paciente", fecha: "2026-03-04T06:25:00", usuario: "Esteban Mora" },
  { id: "e10", trasladoId: "tr4", tipo: "pendiente", descripcion: "Solicitud de traslado creada", fecha: "2026-03-04T04:00:00", usuario: "Maria Lopez" },
  { id: "e11", trasladoId: "tr4", tipo: "asignado", descripcion: "Movil M-04 asignada", fecha: "2026-03-04T04:10:00", usuario: "Carlos Ramirez" },
  { id: "e12", trasladoId: "tr4", tipo: "completado", descripcion: "Traslado completado exitosamente", fecha: "2026-03-04T05:45:00", usuario: "Marco Salazar" },
  { id: "e13", trasladoId: "tr6", tipo: "pendiente", descripcion: "Solicitud de traslado creada", fecha: "2026-03-04T07:00:00", usuario: "Sandra Restrepo" },
  { id: "e14", trasladoId: "tr6", tipo: "asignado", descripcion: "Movil M-01 asignada", fecha: "2026-03-04T07:20:00", usuario: "Carlos Ramirez" },
]
