import type { Patient, Gestion } from "./types"

export const mockPatients: Patient[] = [
  {
    id: "p1",
    bedCode: "UCI-101",
    name: "Carlos Andres Martinez Lopez",
    document: "1.023.456.789",
    age: 45,
    admissionDate: "2026-02-15",
    contractName: "REGIMEN CONTRIBUTIVO",
    company: "Nueva EPS",
  },
  {
    id: "p2",
    bedCode: "UCI-102",
    name: "Maria Fernanda Gomez Rivera",
    document: "52.789.123",
    age: 67,
    admissionDate: "2026-02-10",
    contractName: "REGIMEN SUBSIDIADO",
    company: "Capital Salud",
  },
  {
    id: "p3",
    bedCode: "HOS-201",
    name: "Jorge Enrique Perez Duarte",
    document: "79.654.321",
    age: 33,
    admissionDate: "2026-02-18",
    contractName: "REGIMEN CONTRIBUTIVO",
    company: "Sanitas",
  },
  {
    id: "p4",
    bedCode: "HOS-202",
    name: "Ana Lucia Torres Mendoza",
    document: "39.876.543",
    age: 78,
    admissionDate: "2026-02-08",
    contractName: "REGIMEN CONTRIBUTIVO",
    company: "Sura",
  },
  {
    id: "p5",
    bedCode: "HOS-203",
    name: "Diego Alejandro Ruiz Herrera",
    document: "1.098.765.432",
    age: 28,
    admissionDate: "2026-02-20",
    contractName: "SOAT",
    company: "Seguros del Estado",
  },
  {
    id: "p6",
    bedCode: "PED-301",
    name: "Valentina Sofia Castro Vega",
    document: "1.234.567.890",
    age: 12,
    admissionDate: "2026-02-19",
    contractName: "REGIMEN CONTRIBUTIVO",
    company: "Compensar",
  },
  {
    id: "p7",
    bedCode: "PED-302",
    name: "Santiago David Morales Rios",
    document: "1.111.222.333",
    age: 8,
    admissionDate: "2026-02-21",
    contractName: "REGIMEN SUBSIDIADO",
    company: "Coosalud",
  },
  {
    id: "p8",
    bedCode: "UCI-103",
    name: "Rosa Elena Vargas Pineda",
    document: "41.567.890",
    age: 55,
    admissionDate: "2026-02-05",
    contractName: "POLIZA",
    company: "Colsanitas",
  },
]

export const mockGestiones: Gestion[] = [
  {
    id: "g1",
    code: "GC-2026-001",
    patientId: "p1",
    patientName: "Carlos Andres Martinez Lopez",
    title: "Solicitud de interconsulta cardiologia",
    observation: "Paciente presenta dolor toracico recurrente",
    priority: "ALTA",
    type: "NORMAL",
    area: "Cardiologia",
    status: "EN_PROCESO",
    createdAt: "2026-02-16T10:30:00",
    observations: [
      {
        id: "o1",
        text: "Se solicita valoracion por cardiologia urgente",
        createdAt: "2026-02-16T10:30:00",
        author: "Dr. Rodriguez",
      },
      {
        id: "o2",
        text: "Cardiologia confirma cita para mana a las 8am",
        createdAt: "2026-02-16T14:00:00",
        author: "Enf. Garcia",
      },
    ],
    ambulanceTransfer: null,
  },
  {
    id: "g2",
    code: "GC-2026-002",
    patientId: "p2",
    patientName: "Maria Fernanda Gomez Rivera",
    title: "Traslado a clinica especializada",
    observation: "Requiere cirugia cardiovascular no disponible en la sede",
    priority: "CRITICA",
    type: "TRASLADO_AMBULANCIA",
    area: "Traslados",
    status: "PENDIENTE",
    createdAt: "2026-02-17T08:00:00",
    observations: [],
    ambulanceTransfer: {
      transferType: "SIMPLE",
      reason: "Cirugia cardiovascular de alta complejidad",
      dateTime: "2026-02-18T06:00:00",
      origin: {
        place: "Hospital Central",
        address: "Cra 10 #20-30",
        department: "Cundinamarca",
        municipality: "Bogota",
      },
      destination: {
        place: "Fundacion Cardioinfantil",
        address: "Calle 163A #13B-60",
        department: "Cundinamarca",
        municipality: "Bogota",
      },
      destinationService: "UCI",
      vitalSupport: {
        infusionPump: true,
        mechanicalVentilator: false,
      },
      observation: "Paciente estable pero requiere monitoreo continuo",
      requiresEPP: true,
      trips: [
        {
          id: "t1",
          tripNumber: 1,
          status: "PENDIENTE",
          driver: null,
          origin: "Hospital Central",
          destination: "Fundacion Cardioinfantil",
        },
      ],
    },
  },
  {
    id: "g3",
    code: "GC-2026-003",
    patientId: "p4",
    patientName: "Ana Lucia Torres Mendoza",
    title: "Gestion de ayudas diagnosticas",
    observation: "",
    priority: "MEDIA",
    type: "NORMAL",
    area: "Diagnostico",
    status: "INICIADO",
    createdAt: "2026-02-19T09:15:00",
    observations: [],
    ambulanceTransfer: null,
  },
]
